### ISSUE TITLE
Copy-paste an image results in loosing the "load Equation"

### ISSUE THREAD

**Issue by iron76** [brendena/MathEquationsGoogleSlide#5]
Within Google slides, a copy-pasted equation looses some properties (meta-data?) and the "load Equation" function is no longer working for that particular equations. Similar issue with an equation copied from another.

**Comment by iron76** [comment]
A similar issue is experienced on all equations within a slide if the slide cut and pasted.

**Comment by gavin-s-smith** [comment]
One solution is to store the equation and the colour information in the image url. While I'd prefer it to be stored in the alttext this is much more complex (see https://github.com/brendena/MathEquationsGoogleSlide/issues/6).

In any case storing these in the image URL is relatively simple (if anyone is interested you can see how it is done in [my fork](https://github.com/gavin-s-smith/MathEquationsGoogleSlide). Relevant changes are in `imageLogic.gs` functions `setImage(jsonImageData)` and `getLinkedToImage()`.

However, it is of course a bit of hack and prevents the url being used. If possible I'd prefer to see a solution that involved alttext, but in the short term I'd personally be happy to see the url being used since for me losing the equation when copying and pasting is a deal breaker.

**Comment by brendena** [comment]
This issue was solved by adding image information in the alt text.  (See [#6](https://github.com/brendena/MathEquationsGoogleSlide/issues/6))
