### ISSUE TITLE
Automatically use latex source code as "alternative text"

### ISSUE THREAD

**Issue by ogrisel** [brendena/MathEquationsGoogleSlide#6]
It's possible to put some alt-text for blind people in the "alt text" of the image. You can do so manually by right-clicking on the image and by selecting "alternative text" or by pressing `Ctrl-Alt-Y` when the image is selected. It would be great to put the latex / asciimath source code as alt text of the generated image by default.

**Comment by gavin-s-smith** [comment]
Agreed that this would be very useful.

Unfortunately this does not seem easily possible: The Google Apps Script API for Slides doesn't seem to have the option (see https://developers.google.com/apps-script/reference/slides/image).

It does seem to be possible via the Advanced slide service (https://developers.google.com/apps-script/advanced/slides). However, this requires this to be enabled and as of yet I've been unable to get it to work. The required snippet seems to be (variable Slides exists once you've enabled the Advanced slide service):
 ` var requests = [{
    updatePageElementAltText: {
      objectId: imageSlide.getObjectId(),
      title: jsonImageData["mathEquationColor"],
      description: jsonImageData["mathEquation"],
    }
 
  }];
  // Execute the requests.
  var batchUpdateResponse = Slides.Presentations.batchUpdate({
    requests: requests
  }, SlidesApp.getActivePresentation().getId());
 `
This snippet can go directly at the end of setImage(jsonImageData) in imageLogic.gs 

However, currently this breaks with a object not found error.

For reference that snippet was built from:
https://developers.google.com/slides/how-tos/merge (Example of batchUpdate in Apps Script)
https://developers.google.com/slides/reference/rest/v1/presentations/request#UpdatePageElementAltTextRequest (Documentation for the updatePageElementAltText request from the Slides API)

I leave this here in case anyone can shed some light on the issue. In the meantime, if you are simply wanting a solution to the copy-paste losing the underpinning equation issues (https://github.com/brendena/MathEquationsGoogleSlide/issues/5) then this can be fixed by storing the equation in the image url for which the API has both a set and get method. See: https://github.com/brendena/MathEquationsGoogleSlide/issues/5

**Comment by brendena** [comment]
I've add the Latex to the description and used the title to hold attributes about the image.  I've created a [example project demonstrating](https://github.com/brendena/GoogleExtensionExamples/tree/master/SlidesAltText) it.

[See Changes to Project](https://github.com/brendena/MathEquationsGoogleSlide/commit/cc05ee8081a09489ff641f5ffced3c1f323ad156)

Thanks for the above code.   These changes will be in soon.  I have to verified by google for use with the advance API and fix a few other bugs.
